apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ddivyadharshini28/acadamic-deadline-project-backend:v1.1
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: mongodb://mongodb-service:27017/test
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP